# Generated by Django 4.1.1 on 2022-10-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_alter_studentwork_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwork',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
