# Generated by Django 4.1.1 on 2022-10-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_studentwork_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dataEntrega',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='dataUpload',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentwork',
            name='content',
            field=models.TextField(),
        ),
    ]
