# Generated by Django 4.1.1 on 2022-10-09 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list', '0009_task_dataentrega_task_dataupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.sala'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
