# Generated by Django 4.1.1 on 2022-10-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0013_enrolledcourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentwork',
            name='status',
        ),
    ]
