# Generated by Django 4.1.1 on 2022-10-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
