# Generated by Django 4.1.1 on 2022-10-09 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_sala_alter_usertype_usertype_task_studentwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwork',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='todo_list.task'),
        ),
    ]
