# Generated by Django 4.1.1 on 2022-10-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0014_remove_studentwork_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertype',
            name='spacesCoins',
            field=models.IntegerField(default=0),
        ),
    ]
